### PR TITLE
Add Ctrl+Q=exit, Ctrl+N=New qube, Home & End keys

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/8871

### CODE REVIEW

**Comment by alimirjamali** [comment]
Making pylint happy(er)

**Review by marmarta — APPROVED** [review]

**Comment by marmarta** [comment]
PipelineRetry

**Comment by alimirjamali** [comment]
PipelineRetryFailed

**Review by marmarek — CHANGES_REQUESTED** [review]
Home / End keys behave weirdly. They do scroll the table, but don't move the selection.

**Comment by alimirjamali** [comment]
> Home / End keys behave weirdly. They do scroll the table, but don't move the selection.

I did that intentionally. It is easy to select last/first on Home/End keys if it is better. Amendment will follow shortly.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
