### PR TITLE
Added busy cursor to settings dialog

### PR DESCRIPTION
**Pull request by donob4n**
Hi,
It could be better but it would need pretty big rewrite.

fixes https://github.com/QubesOS/qubes-issues/issues/4744

### CODE REVIEW

**Comment by marmarek** [comment]
Can you provide some timing data? According to @andrewdavidwong [guidelines](https://github.com/QubesOS/qubes-issues/issues/4744#issuecomment-464377415) progress bar is useful if the operation takes over 2s. I haven't managed to make it even over 1s. But it may be that my system is faster...

**Comment by donob4n** [comment]
Yes I did some test and doing almost any possible modification I got between 3 and 4 seconds.

I will improve it with @andrewdavidwong suggestions.

**Comment by donob4n** [comment]
Since it is not likely to spend too much time, the busy cursor seems enough notification so I removed the progress bar.

**Comment by donob4n** [comment]
Don't merge this yet @marmarek I will add busy cursors to some dialogs which take few seconds for appearing (Global settings, Manage templates, Backup,...)

**Comment by donob4n** [comment]
I think it's ready @marmarek , I hope it does not conflict with others PR.

**Pull request merged**
