### PR TITLE
Offset menu from mouse click

### PR DESCRIPTION
**Pull request by unman**
Resolves issue in QubesOS/qubes-issues#1911

### CODE REVIEW

**Comment by jpouellet** [comment]
Does this make it possible for click to register on different element than one under cursor if two ui elements are within 10px of each other?

**Comment by unman** [comment]
On Mon, Apr 03, 2017 at 12:18:24AM -0700, Jean-Philippe Ouellet wrote:
> Does this make it possible for click to register on different element than one under cursor if two ui elements are within 10px of each other?
> 
No, it offsets the menu raise 10px from the point of click. The current
implementation raises the menu AT the clickpoint, resulting in mistaken
selection from menu.

**Comment by woju** [comment]
Since main window is gone, this should be closed. Cc @marmarek.

**Comment by jpouellet** [comment]
See comments here: https://github.com/QubesOS/qubes-manager/pull/19#issuecomment-314916101

**Comment by unman** [comment]
@marmarek This is longstanding bug in Manager, which affects users on stable, I think it should be merged.

**Comment by marmarek** [comment]
See #107

**Pull request closed without merging**
