### PR TITLE
global_settings: expose tint+border configurations

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
@marmarek Am I no longer whitelisted for CI retry commands?

**Comment by marmarek** [comment]
PipelineRetryFailed

**Comment by marmarek** [comment]
PipelineRetryFailed

**Comment by marmarek** [comment]
Log says `Unknown command`, let me investigate...

**Comment by rustybird** [comment]
In case it matters for debugging: I posted the first `PipelineRetryFailed` command while the pipeline still had some running jobs.

**Comment by marmarek** [comment]
try again

**Comment by rustybird** [comment]
PipelineRetryFailed

**Comment by rustybird** [comment]
ty!

**Review by marmarek — APPROVED** [review]

**Pull request merged**
