### PR TITLE
Fixed bug with refresh apps in VM settings

### PR DESCRIPTION
**Pull request by marmarta**
Fixed bug that caused the 'refresh apps' button to stay inactive if
refresh failed, and also rewritten the refresh to refresh for both
current vm's template and the vm itself.
references QubesOS/qubes-issues#4152
fixes QubesOS/qubes-issues#4383

Do not merge before https://github.com/QubesOS/qubes-desktop-linux-common/pull/10 - waiting for it to add dependency.

### CODE REVIEW

**Comment by donob4n** [comment]
Hi, 

since I'm switching all threads to QThread classes, I'm fixing this with two slots/signals, one for notifying success result and other for error.

I hope to have a PR ready soon and this change will conflict :\

**Comment by marmarta** [comment]
Don't worry and make the PR - I'll change this one to match, especially as I'm still waiting on a fix from @marmarek  that's needed to make it truly work anywhere outside one testing machine.

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-desktop-linux-common/pull/10 merged, its part of https://github.com/QubesOS/updates-status/issues/757

**Comment by marmarta** [comment]
@marmarek this can be merged now.

**Comment by marmarek** [comment]
@marmarta this conflicts after merging #132

**Comment by donob4n** [comment]
Hi, this is already fixed in https://github.com/QubesOS/qubes-manager/pull/132. I think it can be closed.

**Comment by marmarta** [comment]
As @donob4n  said, this is already fixed. Closing.

**Pull request closed without merging**
